### PR TITLE
Added NullDecimal. Changed Decimal to implement driver.Valuer.

### PR DESCRIPTION
**Pull request by craigjackson**
From comments in PR 16.

### CODE REVIEW

**Comment by craigjackson** [comment]
#16 breaks implementation of `database/sql`'s `driver.Valuer` interface. This change reverts that and adds NullDecimal to support nullable decimal columns in the database.

**Comment by mayowa** [comment]
Please merge this, it fixes a very annoying and time wasting bug

**Comment by braindev** [comment]
Any thoughts/progress on this?  I need the database support so I'm vendoring a version prior to the `driver.Valuer` interface breakage.

**Comment by lewisporter** [comment]
I would also really like this fixed. It is quite the pain in the arse.

**Comment by victorquinn** [comment]
Hey all, apologies this has gone unmerged for so long!

I recently took over as maintainer of this repo and will be staying more on top of these issues going forward.

**Pull request merged**
