### PR TITLE
Add NewFromInt

### PR DESCRIPTION
**Pull request by mathieupost**
Resolves https://github.com/shopspring/decimal/issues/11

### CODE REVIEW

**Comment by victorquinn** [comment]
First, thanks for the additions!

However, is there a reason you chose `newFromInt` which takes an `int64` and `newFromInt32` which takes an `int`?

Why not `newFromInt` which takes an `int` and `newFromInt64` which takes an `int64`?

If there are precedents elsewhere for this kind of thing elsewhere I could be convinced that it's a good idea, but on my first glance it seems rather confusing to have `newFromInt` which doesn't take an `int` and `newFromInt32` which takes an `int` and no `newFromInt64`

**Comment by victorquinn** [comment]
Just following up here, any reply to the above @mathieupost ?

**Comment by mathieupost** [comment]
Sorry for the late reply, I'm on a holiday at the moment ;)
I named it this way because that was how it was named in https://github.com/shopspring/decimal/issues/11.
And I thought that since int64 is used more as far as I know, it would be cleaner in most code to be able to simply use newFromInt for those.

**Comment by mathieupost** [comment]
@victorquinn any comment on this?

**Comment by Mungrel** [comment]
I agree that `NewFromInt(v int)`, `NewFromInt32(v int32)` and `NewFromInt64(v int64)` would be a more intuitive API.

**Comment by mathieupost** [comment]
Since NewFromFloat uses float64 and most libraries use int64 for integers I'll just keep the NewFromInt(int64) method and remove the NewFromInt32(int32) method, since then it'll be consistent with the rest of the API of this library.

**Comment by Mungrel** [comment]
Looks like you included your `.idea/` directory

**Comment by mathieupost** [comment]
Oops, fixed ;)

**Comment by k1ng440** [comment]
please merge it

**Comment by mwoss** [comment]
Hi @mathieupost, a new maintainer here. Thanks for your contribution. 
May I know what will be the purpose of `NewFromInt` method when `New` method exactly matches the current use case?
If we want to create a more flexible API, maybe we should add `NewFromInt32` too? What do you think?
FYI. @njason

**Comment by mathieupost** [comment]
Hi! This is a long time ago 😅 

I guess the idea was that with the `New` method you have to specify the exponent to `0` which is then kind of a magic number in the code of people using this lib. To me `NewFromInt` would be more clear when reading code where this lib is used.

**Comment by mwoss** [comment]
I think your point is pretty valid. 
What's your opinion about adding both `NewFromInt32` and `NewFromInt` initializer methods? It will much already existing FromFloat methods.

**Comment by mathieupost** [comment]
I could add `NewFromInt32` again. I guess it would indeed be nice to match the Float methods.

**Comment by mwoss** [comment]
IMO, looks legit. : ) Let's wait for Jason's feedback

**Pull request merged**
