### PR TITLE
fix the rounding bug in roundShortest method

### PR DESCRIPTION
**Pull request by dreamerjackson**
optimization roundShortest method  for effectiveness 
which  had apply in  go source code: [go-source-strconv](https://github.com/golang/go/blob/master/src/strconv/ftoa.go#L234)

### CODE REVIEW

**Comment by mwoss** [comment]
Thanks for your contribution @dreamerjackson. Before diving in code review, could you provide proper benchmarks too? So all be aware of the importance of this optimization.

**Comment by dreamerjackson** [comment]
@mwoss  soory, i  check it and find it's about a bug in rounding shortest.    the fix and detail description is there:[go-commit](https://go.googlesource.com/go/+/05092163bb48004fbad847b04c1b0545e3f0189f)
i add the test in Most recent commit

**Comment by dreamerjackson** [comment]
@cmars @chrismrivera @soyangel  the fix can merge?

**Comment by mwoss** [comment]
Hi @dreamerjackson. I kinda forgot about your PR, I apologize. Could you rename the pull request title to match code content? As you said it's about fixing the bug, not optimization at all. Below I provided the additional benchmarks. 

goos: windows
goarch: amd64
pkg: github.com/shopspring/decimal
| Benchmark name        | Loops | Time per op | Memory per op | Alloc per op |
|----------------------------------|---------|-----------|---------|-------------|
| BenchmarkNewFromFloat-8          | 2350124 | 506 ns/op | 48 B/op | 2 allocs/op |
| BenchmarkNewFromFloatBugFix-8 | 2228163 | 539 ns/op | 48 B/op | 2 allocs/op |

**Comment by dreamerjackson** [comment]
@mwoss i have fixed the title description，please review it again , thx~

**Pull request merged**
