### PR TITLE
Add new helper methods: BigInt, BigFloat

### PR DESCRIPTION
**Pull request by mwoss**
Those are requested by the community two new helper methods that would make it easier to use the library and prevent users from making an improper decimal casting. 
In the tests, I used strings for compersion as it is easier to read them in that way and it does not change result of the tests.

### CODE REVIEW

**Comment by njason** [comment]
Or loss of precision

**Comment by mwoss** [comment]
Hm, I wasn't aware that `big.Float` is not available in Go v.1.2. What should we do? Drop support for that version or remove that new functionality? I'm not sure whether `decimal` should be still compatible with over 7 years old version fo Go.

**Comment by mwoss** [comment]
@njason `big.Float` is available from Go version >1.5. I would say it's ok to remove support for such old Go versions and stick to the pattern of other open-source go libraries

**Comment by njason** [comment]
Sounds good to me

**Pull request merged**
